export const AUTHENTICATION = 'AUTHENTICATION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_USERS_DATA = 'GET_USERS_DATA';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_USER_QUESTION = 'SAVE_USER_QUESTION';
export const QUESTION_ANSWER= 'QUESTION_ANSWER';
export const SAVE_USER_ANSWER= 'SAVE_USER_ANSWER';
export const REMOVE_AUTHENTICATION ='REMOVE_AUTHENTICATION';